### ISSUE TITLE
Unspecific 503 error on request() 

### ISSUE THREAD

**Issue by arthosdevelops** [nats-io/nats.deno#342]
While calling the nc.request(msg, data, opts), we randomly face the following 503 error. Previously it would go away with a container restart, but it has been coming up quite often recently and I am not sure where to start debugging since the message is not very descriptive as to point to the root cause of this error. Is this a known error?
```
NatsError: 503
   at NatsError.errorForCode (/crane/node_modules/.pnpm/nats@2.7.1/node_modules/nats/lib/nats-base-client/error.js:100:16)
   at isRequestError (/crane/node_modules/.pnpm/nats@2.7.1/node_modules/nats/lib/nats-base-client/msg.js:29:42)
   at SubscriptionImpl.callback (/crane/node_modules/.pnpm/nats@2.7.1/node_modules/nats/lib/nats-base-client/nats.js:229:56)
   at ProtocolHandler.processMsg (/crane/node_modules/.pnpm/nats@2.7.1/node_modules/nats/lib/nats-base-client/protocol.js:346:17)
   at ProtocolHandler.push (/crane/node_modules/.pnpm/nats@2.7.1/node_modules/nats/lib/nats-base-client/protocol.js:446:22)
   at Parser.parse (/crane/node_modules/.pnpm/nats@2.7.1/node_modules/nats/lib/nats-base-client/parser.js:197:41)
   at ProtocolHandler.<anonymous> (/crane/node_modules/.pnpm/nats@2.7.1/node_modules/nats/lib/nats-base-client/protocol.js:189:45)
   at Generator.next (<anonymous>)
   at fulfilled (/crane/node_modules/.pnpm/nats@2.7.1/node_modules/nats/lib/nats-base-client/protocol.js:5:58)
   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Error
   at NatsConnectionImpl.request (/crane/node_modules/.pnpm/nats@2.7.1/node_modules/nats/lib/nats-base-client/nats.js:216:28)```

**Comment by aricart** [comment]
The issue here is that you are requesting to a subject that no subscriber is listening on.
If I have a simple program like this:

```javascript
const { connect } = require("nats");

(async () => {
  const nc = await connect({ port: 4222 });
  await nc.request("foo"); // <--- this will fail with a 503
  await nc.close();
})();
```

The stack trace that I get is very similar to yours with the exception that the important line trace to give you the source of the error is missing from yours:
```
NatsError: 503
    at Function.errorForCode (/private/tmp/request/node_modules/nats/lib/nats-base-client/error.js:100:16)
    at isRequestError (/private/tmp/request/node_modules/nats/lib/nats-base-client/msg.js:29:42)
    at SubscriptionImpl.callback (/private/tmp/request/node_modules/nats/lib/nats-base-client/nats.js:229:56)
    at ProtocolHandler.processMsg (/private/tmp/request/node_modules/nats/lib/nats-base-client/protocol.js:346:17)
    at ProtocolHandler.push (/private/tmp/request/node_modules/nats/lib/nats-base-client/protocol.js:446:22)
    at Parser.parse (/private/tmp/request/node_modules/nats/lib/nats-base-client/parser.js:197:41)
    at ProtocolHandler.<anonymous> (/private/tmp/request/node_modules/nats/lib/nats-base-client/protocol.js:189:45)
    at Generator.next (<anonymous>)
    at fulfilled (/private/tmp/request/node_modules/nats/lib/nats-base-client/protocol.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Error
    at NatsConnectionImpl.request (/private/tmp/request/node_modules/nats/lib/nats-base-client/nats.js:216:28)
    at /private/tmp/request/test.js:5:12 <------ The error
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: '503',
  chainedError: undefined

```

Can you try running the snippet above, and verify that you are getting the same tracing information.
Also you are not using the default, npm,  I am wondering if there's some sort of

**Comment by aricart** [comment]
If your service is part of some assembly it is possible that the service is not ready or has crashed at the time of the request.
