### ISSUE TITLE
Closed connection with 'Stale Connection' error doesn't auto-reconnect

### ISSUE THREAD

**Issue by ArmorDarks** [nats-io/nats.deno#421]
* Client version: 2.8.0
* Node version: 16.14.2

## What's happening

Given the config

```ts
const connection = await connect({
  maxReconnectAttempts: -1,
  name: 'some-name',
  pass: 'some-pass',
  servers: ['load-balancer-url'],
  user: 'some-user',
  inboxPrefix: 'some.inbox',
})
```

If the connection closed with the following error

```
NatsError: 'Stale Connection'
    at Function.toError (/code/node_modules/nats/lib/nats-base-client/protocol.js:339:20)
    at ProtocolHandler.<anonymous> (/code/node_modules/nats/lib/nats-base-client/protocol.js:363:41)
    at Generator.next (<anonymous>)
    at /code/node_modules/nats/lib/nats-base-client/protocol.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/code/node_modules/nats/lib/nats-base-client/protocol.js:4:12)
    at ProtocolHandler.processError (/code/node_modules/nats/lib/nats-base-client/protocol.js:361:16)
    at ProtocolHandler.push (/code/node_modules/nats/lib/nats-base-client/protocol.js:461:22)
    at Parser.parse (/code/node_modules/nats/lib/nats-base-client/parser.js:307:45)
    at ProtocolHandler.<anonymous> (/code/node_modules/nats/lib/nats-base-client/protocol.js:197:45)
```

it will never reconnect despite `maxReconnectAttempts` set to `-1`

## What's expected

If `maxReconnectAttempts` set to `-1`, the connection should automatically try reconnecting. Otherwise, it should be highlighted in the docs that this particular case has to be handled manually.

**Comment by aricart** [comment]
@ArmorDarks `npm install nats@latest` - I think we are finally sorted out (famous words) - thank you for your enduring help.

**Comment by ArmorDarks** [comment]
@aricart Nice, looks like it will fix plenty of other odd behaviors with server-side errors too. Thanks!
